### ISSUE TITLE
Update version number of snap for different operating systems. 

### ISSUE THREAD

**Issue by nottrobin** [canonical-docs/snappy-docs#152]
_From @rajudev on August 15, 2017 20:38_

## Summary
The version numbers mentioned in docs here https://snapcraft.io/docs/core/install have now changed. 
The numbers mentioned in the documentation are now lagging a lot behind the actual version of snap. 

## Process

[list the steps to replicate the issue]
visit https://snapcraft.io/docs/core/install

## Current and expected result
For Debian
Version of snap mentioned for Debian Unstable is 2.21
while the actual version present right now is [2.27](https://tracker.debian.org/pkg/snapd)
similarly it should be changed for all other operating systems

## Screenshot
Too lazy to do this. Take a look at the links

_Copied from original issue: canonical-webteam-archive/snapcraft.io-static-pages#360_

**Comment by evilnick** [comment]
Hmm. Can I ask what the point of the version table is? (I get the point of the notes). This just seems to be something that will likely be permanently out of date, easy for the user to check for themselves and virtually impossible for the docs team to actually track

**Comment by matthewpaulthomas** [comment]
I don’t know why the table was added originally, but:

- Snap interfaces are introduced in snapd versions. If the snap you want to publish requires a particular interface, and a particular OS version doesn’t have a version of snapd with that interface, you’ll want to know, so that you can decide whether/how to provide your software to users of that OS version.

- As shown in the table, several OSes don’t currently allow snaps with classic confinement. If your snap uses classic confinement, and a particular OS version doesn’t allow classic snaps, you’ll want to know, so that you can decide whether/how to provide your software to users of that OS version.

Even if either of those things fit into the category “easy for the user to check for themselves on their own OS”, they don’t fit into the category “easy for a developer to check for themselves on every OS”, which is probably more important since this is a developer site.

**Comment by evilnick** [comment]
That would make sense except the interfaces aren't listed here, so it isn't helpful in that respect at all, and like I said, it will be constantly out of date.

We could rework the table to list versions and their salient features (interfaces, supported modes). That would require updating only when new versions came out. This would seem to be more maintainable and more useful.

**Comment by matthewpaulthomas** [comment]
> except the interfaces aren't listed here, so it isn't helpful in that respect at all

To clarify, I think the use case is “I want to be told how using X will affect the addressable market for my snap”.

If X = “a particular interface”, then I’m most likely to be looking at information about the interface. So mentioning the interface in the version table would be the wrong way around: I already know what version the interface was introduced in, since it’s mentioned on the interface page. An ideal would be text on the interface page, something like “Currently available to ___% of users”, linking _to_ the OS version table to explain where that figure comes from. Next best would be linking to the version table without providing a summary percentage.

Similarly, if X = “classic confinement”, then I’m most likely to be looking at information about confinement. So again, the ideal would be a summary percentage and link from that page _to_ the version table, but any link to the table would be better than none.

I realize all this is really difficult! But also really important, because it also helps answer the question: “Is it practical for me to use a snap for my software in the first place?” Getting back to the original problem,
> and like I said, it will be constantly out of date

keeping the version table up to date in future seems like something that could be at least _partly_ automated with shell scripts periodically pinging the archives of each OS.

**Comment by matthewpaulthomas** [comment]
@popey removed the table altogether in #401. So the problem of “The numbers mentioned in the documentation … lagging a lot behind the actual version” is literally fixed.

(The same week, @popey & co. did the research required to update the table.)

Besides the developer use cases above for tracking this information, we now have [snap directory pages for end users](https://snapcraft.io/store), which introduces two more use cases:
- End user doesn’t know whether they have snapd, but they know what OS version they’re using. They should see relevant instructions.
- End user doesn’t know whether a particular snap works with their combination of OS (_e.g._ classic confinement) and snapd version (_e.g._ new interfaces). If it won’t, they should see some sort of warning and/or update instructions.
