### ISSUE TITLE
Templates for repetitive pages

### ISSUE THREAD

**Issue by IvanFon** [canonical-docs/snappy-docs#261]
Some parts of the documentation, such as the [language tutorials](https://docs.snapcraft.io/build-snaps/languages) and the [plugins reference](https://docs.snapcraft.io/reference/plugins/) have many pages, all of which maintain at least some of the same structure/content. Recently I made changes to some repeated parts of the language tutorials (#254, #255), and I had to change every single page, even though it was the same content.

With that said, would it be possible to create templates for pages with repeated portions? I'm not completely sure how the documentation build system works, so I'm not sure how feasible this idea is. I do see the includes and layouts, but I'm not sure if those would be suitable for this purpose. Perhaps someone more knowledgeable would be able to help out?

Thanks!

**Comment by evandandrea** [comment]
Yeah, this is by design. We want the guides to be self contained, so that you can read one without having to jump around.

They should also diverge from each other where it helps speak to the specific language audience. We want to avoid speaking generically. For example, we explain how this relates to pip, virtualenv, etc so Python developers understand where this fits in their tool belt. We explain bundling system libraries in C apps, but not Java ones (where it's irrelevant).

I know updating a few pages for a change takes more time, but it's an investment well made.

**Comment by evandandrea** [comment]
And thank you for those PRs! Great contribution.

**Comment by nottrobin** [comment]
@IvanFon in this case, the docs codebase is simply a Jekyll site, so in cases where large blocks of text are exactly duplicated, you *can* use [Jekyll's (Liquid) include syntax](https://jekyllrb.com/docs/includes/) to share those blocks as includes.

However, there's a trade-off here - by creating an include you make it so that document can no longer be read as one single file of Markdown, and it's more complicate for people to find and make changes to that piece of text.

In the two cases you highlight, the duplication is really just 1-3 lines. I really think the downsides of creating includes outweigh the benefits - it's better for these pages to remain direct, and keep the ability to have nuanced differences in their advice and wording.

But if you spot other cases where significant blocks are duplicated, I'd say feel free to make use of Jekyll templates in your PRs, and see what the reviewers think.
